### PR TITLE
[FIX] make dependent wire limits actually dependent

### LINKED ISSUE #102: race condition with blockchain.New() writing to wire package variables
I hesitate to file this. Maybe it is good to be searchable and it also might show a class of race conditions involving package level variables.

The race detector (`go test -race ./...`) found a race condition:

- `blockchain.New()` sets some variables in the `wire` package.
- The detector specifically caught `wire.MaxMessagePayload` being read and written by two different tests.

That wouldn't matter if, for example, `blockchain.New()` is only called once, but I found it it used in:

- `cmd/addblock/import.go`
- `cmd/findcheckoint/findcheckpoint.go`
- and of course `server.go`

So there is a remote chance of mangled data using those commands. There also might be a class of problems with package variables.

### PR DESCRIPTION
**Pull request by emergent-reasons**
Fixes #102, #110 

This is more of a request for feedback. As described in #102, the race condition is not such a big deal - it's more of a test issue. However it showed more importantly that there are many fake static configuration values as documented in #110.

I tried 3 ways to fix it with minimal changes:

1. Threading the EBS dependency into everything that needs it. This just made the `wire` package a mess and made it harder to use as well.

1. (This PR) Initializing EBS in the wire package explicitly. This is a pain because everyone that uses it has to initialize the package. However, it turned out to be the cleanest fix that I found.

1. [Refactor a new `config` package](https://github.com/gcash/bchd/compare/master...emergent-reasons:isolate-config) so that any package can get EBS and other config values. This would have the benefit of reducing quite a bit of redundant configuration loading code in the commands. It also would be nice to have config decoupled from CLI code. However, I ran into an import cycle (`wire-->config-->chaincfg-->wire` and stopped at that point.

I am hoping someone has a more elegant / simple way to solve these issues, especially #110.

### CODE REVIEW

**Comment by emergent-reasons** [comment]
@cpacia, regarding the alerts in `wire`, should I just basically pull out all `msgalert.go` related code?

**Comment by cpacia** [comment]
Yeah I think so

**Comment by emergent-reasons** [comment]
> Yeah I think so

I'm not sure this PR will get merged but the alerts should be removed so --> #133

**Comment by zquestz** [comment]
I think this is considerably better than how these values are set today. I would be a fan of merging this approach. @cpacia what are your thoughts on this?

**Comment by cpacia** [comment]
Will review my end of the week

File: blockchain/chain_test.go [hunk 1]
```diff
@@ -15,6 +15,12 @@ import (
 	"github.com/gcash/bchutil"
 )
 
+const fixedExcessiveBlockSize uint32 = 64000000
```
Comment (zquestz) [inline blockchain/chain_test.go]: All these test invocations could be removed by putting in a default if the value is not set.

File: wire/message.go [hunk 2]
```diff
@@ -22,9 +22,28 @@ const MessageHeaderSize = 24
...
+
+// SetLimits initializes various message limits which change depending on the maximum
+// block size we will deal with.
+func SetLimits(excessiveBlockSize uint32) {
+	ebs = excessiveBlockSize
+}
+
+func getEBS() uint32 {
+	if ebs == 0 {
+		panic("message size limits have not been initialized")
```
Comment (zquestz) [inline wire/message.go]: Set a reasonable default here and don't panic. Then you don't need to init the tests.

File: wire/message.go [hunk 3]
```diff
@@ -22,9 +22,28 @@ const MessageHeaderSize = 24
...
+// ebs is the excessive block size, used to determine reasonable maximum message sizes.
+var ebs uint32
+
+// SetLimits initializes various message limits which change depending on the maximum
+// block size we will deal with.
+func SetLimits(excessiveBlockSize uint32) {
+	ebs = excessiveBlockSize
+}
+
+func getEBS() uint32 {
```
Comment (zquestz) [inline wire/message.go]: We should export this and just call it `EBS()`. I want to add support for the UserAgent and will need that in `peer.go` =)

File: wire/message.go (hunk 2 above)
Comment (emergent-reasons) [reply wire/message.go]: If we do that, it is equivalent to the original usage of defaults which ignores actual EBS and we are in the same position as before. Any case where it is not set, the behavior becomes out of spec. I thought failing loudly and explicitly would be better than running outside spec?

File: wire/message.go (hunk 3 above)
Comment (emergent-reasons) [reply wire/message.go]: Ok. Also if we will use a default as above, then I will just remove this getter.

File: wire/message.go (hunk 2 above)
Comment (emergent-reasons) [reply wire/message.go]: (it's a little better since all the values are actually dependent on the default instead of manually calculated across constants.)

File: blockchain/chain_test.go (hunk 1 above)
Comment (emergent-reasons) [reply blockchain/chain_test.go]: I put this to make sure we test something besides the default EBS. I should probably set it to some odd value that will never be the actual default.

If I add a little documentation to the constant, would that be ok with you?

```go
// fixedExcessiveBlockSize should not be the default to ensure it will work in all cases
```

Comment (zquestz) [reply blockchain/chain_test.go]: That is super reasonable =)

File: wire/message.go (hunk 2 above)
Comment (zquestz) [reply wire/message.go]: You already do a sanity check of the value when it is read from the config. Since we know we are going to set it to a reasonable value I have no problem with a default here. =)

File: wire/message.go (hunk 3 above)
Comment (zquestz) [reply wire/message.go]: Yep that works.

**Comment by emergent-reasons** [comment]
@zquestz I rebased and tried to fix all the issues above.

File: wire/message.go (hunk 3 above)
Comment (emergent-reasons) [reply wire/message.go]: removed the getter

File: wire/message.go (hunk 2 above)
Comment (emergent-reasons) [reply wire/message.go]: used and documented a default on `var ebs`

File: blockchain/chain_test.go (hunk 1 above)
Comment (emergent-reasons) [reply blockchain/chain_test.go]: done. I think,
